{% set name = "pydantic-cli" %}
{% set version = "9.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_cli-{{ version }}.tar.gz
  sha256: 1f0bb76496ff506a6adf7abe4f28b711c7517e438e5171622b3c51a91806862c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatch
  run:
    - pydantic >=2.8.2
    - python >=3.7
    # - shtab >=1.3.1
    # - pytest >=6.0.1
    # - mypy >=0.930
    # - black >=21.7b0
    # - shtab >=1.3.1
    # - pytest-cov >=4.0.0
    # - pytest >=8.2.2
    # - mypy >=1.10.1
    # - black >=24.4.2

test:
  imports:
    - pydantic_cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/mpkocher/pydantic-cli
  summary: Turn Pydantic defined Data Models into CLI Tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
