{% set name = "pydantic-cli" %}
{% set version = "4.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic_cli-{{ version }}.tar.gz
  sha256: 6e43a4e1ef04f95656a1ac291e71d928d759c4701262872115b56d57e2fcc880

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pydantic <2,>=1.5
    - python >={{ python_min }}
    # - shtab >=1.3.1
    # - pytest >=6.0.1
    # - mypy >=0.930
    # - black >=21.7b0

test:
  imports:
    - pydantic_cli
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/mpkocher/pydantic-cli
  summary: Turn Pydantic defined Data Models into CLI Tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
